APT::FTPArchive::Release::Origin "Pho Repo";
APT::FTPArchive::Release::Label "Pho Repo";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Version "1.0";
APT::FTPArchive::Release::Codename "ios-iphone";
APT::FTPArchive::Release::Architectures "iphoneos-arm iphoneos-arm64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Sileo Repository";
